services:
  - type: web
    name: casebot-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=5000
    envVars:
      - key: FLASK_APP
        value: app.py
    disk:
      name: casebot-data
      mountPath: /data
      sizeGB: 1

  - type: cron
    name: casebot-fetch
    env: python
    plan: free
    schedule: "0 5 * * *" # every day at 5am UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python casebot_engine.py
    disk:
      name: casebot-data
      mountPath: /data
      sizeGB: 1
